export struct SlintViewport {
    x1: float,
    y1: float,
    dx: float,
    dy: float,
}

export component ViewArea inherits TouchArea {
    in-out property <SlintViewport> viewport;
    in property <bool> enable-panning: true;

    callback moved2;

    // last-* is used to track the previous positive during panning.
    property <length> last-x;
    property <length> last-y;
                        
    pointer-event(event) => {
        if (event.kind == PointerEventKind.down) {
            self.last-x = self.mouse-x;
            self.last-y = self.mouse-y;    
        }
    }
    
    moved => {
        if (self.enable-panning) {
            self.viewport.x1 -= (self.mouse-x - self.last-x) / self.width * self.viewport.dx * max(1.0, self.width/self.height);
            self.viewport.y1 -= (self.mouse-y - self.last-y) / self.height * self.viewport.dy * max(1.0, self.height/self.width);
        }
        self.last-x = self.mouse-x;
        self.last-y = self.mouse-y;
        moved2();
    }
}